# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
- binary: learn
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  - freebsd
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: learn
    tap:
      owner: gSchool
      name: homebrew-glearn
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    folder: Formula
    description: "Learn curriculum publishing tool © Galvanize, Inc."
    dependencies:
      - git
      - zsh
    install: |
      bin.install "learn"
